# Generated by Django 5.1.1 on 2025-04-21 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dogs", "0002_alter_dog_breed"),
        ("prediction", "0010_alter_prediction_request_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("골든 리트리버", "골든 리트리버"),
                            ("래브라도 리트리버", "래브라도 리트리버"),
                            ("푸들", "푸들"),
                            ("포메라니안", "포메라니안"),
                            ("말티즈", "말티즈"),
                            ("시추", "시추"),
                            ("요크셔 테리어", "요크셔 테리어"),
                            ("비숑 프리제", "비숑 프리제"),
                            ("웰시 코기", "웰시 코기"),
                            ("프렌치 불도그", "프렌치 불도그"),
                            ("치와와", "치와와"),
                            ("미니어처 핀셔", "미니어처 핀셔"),
                            ("미니어처 슈나우저", "미니어처 슈나우저"),
                            ("시바 이누", "시바 이누"),
                            ("닥스훈트", "닥스훈트"),
                            ("보더 콜리", "보더 콜리"),
                            ("저먼 셰퍼드", "저먼 셰퍼드"),
                            ("도베르만", "도베르만"),
                            ("잭 러셀 테리어", "잭 러셀 테리어"),
                            ("시베리안 허스키", "시베리안 허스키"),
                            ("기타", "기타"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="견종",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True,
                        choices=[("eye", "안구"), ("skin", "피부")],
                        max_length=10,
                        null=True,
                        verbose_name="질환 부위",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_categories",
                        to="prediction.diseaseinfo",
                        verbose_name="질환",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 카테고리",
                "verbose_name_plural": "게시글 카테고리",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="이미지 경로"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="dogs.dog",
                        verbose_name="반려견",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="post.postcategory",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글",
            },
        ),
    ]
