# Generated by Django 5.1.1 on 2025-04-21 07:19

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_remove_post_category_post_body_part_post_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=post.models.post_image_upload_path,
                verbose_name="이미지",
            ),
        ),
    ]
