# Generated by Django 4.2.20 on 2025-04-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimalHospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="병원명")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="전화번호")),
                ("raw_address", models.CharField(max_length=200, verbose_name="소재지(Excel)")),
                (
                    "license_no",
                    models.CharField(blank=True, max_length=50, verbose_name="인허가번호"),
                ),
                (
                    "full_address",
                    models.CharField(blank=True, max_length=300, verbose_name="상세주소"),
                ),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="위도")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="경도")),
            ],
        ),
    ]
