# Generated by Django 4.2.20 on 2025-04-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalhospital",
            name="license_no",
            field=models.CharField(max_length=50, verbose_name="인허가번호"),
        ),
    ]
