# Generated by Django 4.2.20 on 2025-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0002_alter_animalhospital_license_no"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalhospital",
            options={"verbose_name": "동물병원", "verbose_name_plural": "동물병원 목록"},
        ),
        migrations.AlterField(
            model_name="animalhospital",
            name="raw_address",
            field=models.CharField(max_length=200, verbose_name="소재지"),
        ),
    ]
